### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by guranshdeol** [guranshdeol/SCM-Project-Music-Player#3]
there is some issue in linking of javascript file.

**Comment by Worstsniper** [comment]
i had pulled a request solving the above issue:)

**Comment by Worstsniper** [comment]
i had pulled a request solving the above issue:)

**Comment by Worstsniper** [comment]
Kindly Acknowledge it.

**Comment by guranshdeol** [comment]
Thanks for your contribution:)
