### ISSUE TITLE
Spelling Error of Text

### ISSUE THREAD

**Issue by guranshdeol** [guranshdeol/SCM-Project-Music-Player#4]
![image](https://user-images.githubusercontent.com/91736425/168730561-b9a75b35-24cd-4d5f-b368-9f23a8d5b5cd.png)

**Comment by shirviverma** [comment]
I had pulled a request solving this issue

kindly accept the Pull request and merge it in your repositry:)

**Comment by guranshdeol** [comment]
Thanks for contributing:)
